insert into Industries (IndustryDesc) values ('SURGICAL & MEDICAL INSTRUMENTS & APPARATUS');
insert into Industries (IndustryDesc) values ('HOUSEHOLD APPLIANCES');
insert into Industries (IndustryDesc) values ('PHARMACEUTICAL PREPARATIONS');
insert into Industries (IndustryDesc) values ('SERVICES-BUSINESS SERVICES, NEC');
insert into Industries (IndustryDesc) values ('SERVICES-PREPACKAGED SOFTWARE');
insert into Industries (IndustryDesc) values ('FATS & OILS');
insert into Industries (IndustryDesc) values ('RETAIL-AUTO & HOME SUPPLY STORES');
insert into Industries (IndustryDesc) values ('SEMICONDUCTORS & RELATED DEVICES');
insert into Industries (IndustryDesc) values ('COGENERATION SERVICES & SMALL POWER PRODUCERS');
insert into Industries (IndustryDesc) values ('ACCIDENT & HEALTH INSURANCE');
insert into Industries (IndustryDesc) values ('INSTRUMENTS FOR MEAS & TESTING OF ELECTRICITY & ELEC SIGNALS');
insert into Industries (IndustryDesc) values ('INDUSTRIAL INORGANIC CHEMICALS');
insert into Industries (IndustryDesc) values ('AIR TRANSPORTATION, SCHEDULED');
insert into Industries (IndustryDesc) values ('PLASTIC MATERIALS, SYNTH RESINS & NONVULCAN ELASTOMERS');
insert into Industries (IndustryDesc) values ('REAL ESTATE INVESTMENT TRUSTS');
insert into Industries (IndustryDesc) values ('ORTHOPEDIC, PROSTHETIC & SURGICAL APPLIANCES & SUPPLIES');
insert into Industries (IndustryDesc) values ('SERVICES-DETECTIVE, GUARD & ARMORED CAR SERVICES');
insert into Industries (IndustryDesc) values ('ELECTRIC & OTHER SERVICES COMBINED');
insert into Industries (IndustryDesc) values ('FIRE, MARINE & CASUALTY INSURANCE');
insert into Industries (IndustryDesc) values ('SERVICES-COMPUTER PROGRAMMING, DATA PROCESSING, ETC.');
insert into Industries (IndustryDesc) values ('CIGARETTES');
insert into Industries (IndustryDesc) values ('RETAIL-CATALOG & MAIL-ORDER HOUSES');
insert into Industries (IndustryDesc) values ('MISCELLANEOUS MANUFACTURING INDUSTRIES');
insert into Industries (IndustryDesc) values ('ELECTRIC SERVICES');
insert into Industries (IndustryDesc) values ('FINANCE SERVICES');
insert into Industries (IndustryDesc) values ('WATER SUPPLY');
insert into Industries (IndustryDesc) values ('INVESTMENT ADVICE');
insert into Industries (IndustryDesc) values ('WHOLESALE-DRUGS, PROPRIETARIES & DRUGGISTS SUNDRIES');
insert into Industries (IndustryDesc) values ('INDUSTRIAL INSTRUMENTS FOR MEASUREMENT, DISPLAY, AND CONTROL');
insert into Industries (IndustryDesc) values ('BIOLOGICAL PRODUCTS, (NO DISGNOSTIC SUBSTANCES)');
insert into Industries (IndustryDesc) values ('ELECTRONIC CONNECTORS');
insert into Industries (IndustryDesc) values ('INSURANCE AGENTS, BROKERS & SERVICE');
insert into Industries (IndustryDesc) values ('CRUDE PETROLEUM & NATURAL GAS');
insert into Industries (IndustryDesc) values ('ELECTRONIC COMPUTERS');
insert into Industries (IndustryDesc) values ('MOTOR VEHICLE PARTS & ACCESSORIES');
insert into Industries (IndustryDesc) values ('COMPUTER COMMUNICATIONS EQUIPMENT');
insert into Industries (IndustryDesc) values ('INSURANCE CARRIERS, NEC');
insert into Industries (IndustryDesc) values ('TELEPHONE COMMUNICATIONS (NO RADIOTELEPHONE)');
insert into Industries (IndustryDesc) values ('NATURAL GAS DISTRIBUTION');
insert into Industries (IndustryDesc) values ('SERVICES-COMPUTER PROCESSING & DATA PREPARATION');
insert into Industries (IndustryDesc) values ('CONVERTED PAPER & PAPERBOARD PRODS (NO CONTANERS/BOXES)');
insert into Industries (IndustryDesc) values ('OIL & GAS FIELD MACHINERY & EQUIPMENT');
insert into Industries (IndustryDesc) values ('NATIONAL COMMERCIAL BANKS');
insert into Industries (IndustryDesc) values ('RETAIL-WOMENS CLOTHING STORES');
insert into Industries (IndustryDesc) values ('RETAIL-RADIO, TV & CONSUMER ELECTRONICS STORES');
insert into Industries (IndustryDesc) values ('LABORATORY ANALYTICAL INSTRUMENTS');
insert into Industries (IndustryDesc) values ('SECURITY BROKERS, DEALERS & FLOTATION COMPANIES');
insert into Industries (IndustryDesc) values ('STATE COMMERCIAL BANKS');
insert into Industries (IndustryDesc) values ('AIRCRAFT');
insert into Industries (IndustryDesc) values ('TRANSPORTATION SERVICES');
insert into Industries (IndustryDesc) values ('ARRANGEMENT OF TRANSPORTATION OF FREIGHT & CARGO');
insert into Industries (IndustryDesc) values ('HOTELS & MOTELS');
insert into Industries (IndustryDesc) values ('FOOD AND KINDRED PRODUCTS');
insert into Industries (IndustryDesc) values ('RETAIL-AUTO DEALERS & GASOLINE STATIONS');
insert into Industries (IndustryDesc) values ('WATER TRANSPORTATION');
insert into Industries (IndustryDesc) values ('AIR-COND & WARM AIR HEATG EQUIP & COMM & INDL REFRIG EQUIP');
insert into Industries (IndustryDesc) values ('CONSTRUCTION MACHINERY & EQUIP');
insert into Industries (IndustryDesc) values ('SECURITY & COMMODITY BROKERS, DEALERS, EXCHANGES & SERVICES');
insert into Industries (IndustryDesc) values ('REAL ESTATE');
insert into Industries (IndustryDesc) values ('PLASTIC MATERIAL, SYNTH RESIN/RUBBER, CELLULOS (NO GLASS)');
insert into Industries (IndustryDesc) values ('HOSPITAL & MEDICAL SERVICE PLANS');
insert into Industries (IndustryDesc) values ('AGRICULTURAL CHEMICALS');
insert into Industries (IndustryDesc) values ('SERVICES-COMMERCIAL PHYSICAL & BIOLOGICAL RESEARCH');
insert into Industries (IndustryDesc) values ('CABLE & OTHER PAY TELEVISION SERVICES');
insert into Industries (IndustryDesc) values ('PETROLEUM REFINING');
insert into Industries (IndustryDesc) values ('RETAIL-EATING PLACES');
insert into Industries (IndustryDesc) values ('SOAP, DETERGENTS, CLEANG PREPARATIONS, PERFUMES, COSMETICS');
insert into Industries (IndustryDesc) values ('MENS & BOYS FURNISHGS, WORK CLOTHG, & ALLIED GARMENTS');
insert into Industries (IndustryDesc) values ('SPECIALTY CLEANING, POLISHING AND SANITATION PREPARATIONS');
insert into Industries (IndustryDesc) values ('BEVERAGES');
insert into Industries (IndustryDesc) values ('SERVICES-COMPUTER PROGRAMMING SERVICES');
insert into Industries (IndustryDesc) values ('PERFUMES, COSMETICS & OTHER TOILET PREPARATIONS');
insert into Industries (IndustryDesc) values ('DRAWING & INSULATING OF NONFERROUS WIRE');
insert into Industries (IndustryDesc) values ('AGRICULTURAL PRODUCTION-CROPS');
insert into Industries (IndustryDesc) values ('RETAIL-VARIETY STORES');
insert into Industries (IndustryDesc) values ('RAILROADS, LINE-HAUL OPERATING');
insert into Industries (IndustryDesc) values ('ENGINES & TURBINES');
insert into Industries (IndustryDesc) values ('RETAIL-DRUG STORES AND PROPRIETARY STORES');
insert into Industries (IndustryDesc) values ('OPERATIVE BUILDERS');
insert into Industries (IndustryDesc) values ('SERVICES-MISC HEALTH & ALLIED SERVICES, NEC');
insert into Industries (IndustryDesc) values ('FARM MACHINERY & EQUIPMENT');
insert into Industries (IndustryDesc) values ('DENTAL EQUIPMENT & SUPPLIES');
insert into Industries (IndustryDesc) values ('PERSONAL CREDIT INSTITUTIONS');
insert into Industries (IndustryDesc) values ('WHOLESALE-GROCERIES & RELATED PRODUCTS');
insert into Industries (IndustryDesc) values ('CONSTRUCTION, MINING & MATERIALS HANDLING MACHINERY & EQUIP');
insert into Industries (IndustryDesc) values ('MISC INDUSTRIAL & COMMERCIAL MACHINERY & EQUIPMENT');
insert into Industries (IndustryDesc) values ('ELECTRONIC & OTHER ELECTRICAL EQUIPMENT (NO COMPUTER EQUIP)');
insert into Industries (IndustryDesc) values ('SERVICES-CONSUMER CREDIT REPORTING, COLLECTION AGENCIES');
insert into Industries (IndustryDesc) values ('RETAIL-BUILDING MATERIALS, HARDWARE, GARDEN SUPPLY');
insert into Industries (IndustryDesc) values ('AIR COURIER SERVICES');
insert into Industries (IndustryDesc) values ('CHEMICALS & ALLIED PRODUCTS');
insert into Industries (IndustryDesc) values ('MOTOR VEHICLES & PASSENGER CAR BODIES');
insert into Industries (IndustryDesc) values ('COMPUTER PERIPHERAL EQUIPMENT, NEC');
insert into Industries (IndustryDesc) values ('TELEVISION BROADCASTING STATIONS');
insert into Industries (IndustryDesc) values ('METAL MINING');
insert into Industries (IndustryDesc) values ('RETAIL-FAMILY CLOTHING STORES');
insert into Industries (IndustryDesc) values ('SEARCH, DETECTION, NAVAGATION, GUIDANCE, AERONAUTICAL SYS');
insert into Industries (IndustryDesc) values ('SERVICES-MANAGEMENT SERVICES');
insert into Industries (IndustryDesc) values ('MOTORS & GENERATORS');
insert into Industries (IndustryDesc) values ('SHIP & BOAT BUILDING & REPAIRING');
insert into Industries (IndustryDesc) values ('GRAIN MILL PRODUCTS');
insert into Industries (IndustryDesc) values ('WHOLESALE-MOTOR VEHICLE SUPPLIES & NEW PARTS');
insert into Industries (IndustryDesc) values ('LIFE INSURANCE');
insert into Industries (IndustryDesc) values ('OIL & GAS FIELD SERVICES, NEC');
insert into Industries (IndustryDesc) values ('RETAIL-APPAREL & ACCESSORY STORES');
insert into Industries (IndustryDesc) values ('GAMES, TOYS & CHILDRENS VEHICLES (NO DOLLS & BICYCLES)');
insert into Industries (IndustryDesc) values ('SERVICES-GENERAL MEDICAL & SURGICAL HOSPITALS, NEC');
insert into Industries (IndustryDesc) values ('WHOLESALE-MEDICAL, DENTAL & HOSPITAL EQUIPMENT & SUPPLIES');
insert into Industries (IndustryDesc) values ('COMPUTER & OFFICE EQUIPMENT');
insert into Industries (IndustryDesc) values ('X-RAY APPARATUS & TUBES & RELATED IRRADIATION APPARATUS');
insert into Industries (IndustryDesc) values ('RETAIL-LUMBER & OTHER BUILDING MATERIALS DEALERS');
insert into Industries (IndustryDesc) values ('AIRCRAFT ENGINES & ENGINE PARTS');
insert into Industries (IndustryDesc) values ('MEAT PACKING PLANTS');
insert into Industries (IndustryDesc) values ('ROLLING DRAWING & EXTRUDING OF NONFERROUS METALS');
insert into Industries (IndustryDesc) values ('PUMPS & PUMPING EQUIPMENT');
insert into Industries (IndustryDesc) values ('IN VITRO & IN VIVO DIAGNOSTIC SUBSTANCES');
insert into Industries (IndustryDesc) values ('GENERAL INDUSTRIAL MACHINERY & EQUIPMENT');
insert into Industries (IndustryDesc) values ('INDUSTRIAL ORGANIC CHEMICALS');
insert into Industries (IndustryDesc) values ('PAPER MILLS');
insert into Industries (IndustryDesc) values ('SERVICES-ADVERTISING AGENCIES');
insert into Industries (IndustryDesc) values ('TRUCKING (NO LOCAL)');
insert into Industries (IndustryDesc) values ('SERVICES-COMPUTER INTEGRATED SYSTEMS DESIGN');
insert into Industries (IndustryDesc) values ('HEAVY CONSTRUCTION OTHER THAN BLDG CONST - CONTRACTORS');
insert into Industries (IndustryDesc) values ('CANNED, FRUITS, VEG, PRESERVES, JAMS & JELLIES');
insert into Industries (IndustryDesc) values ('SERVICES-MISCELLANEOUS BUSINESS SERVICES');
insert into Industries (IndustryDesc) values ('NATURAL GAS TRANSMISSION');
insert into Industries (IndustryDesc) values ('OPTICAL INSTRUMENTS & LENSES');
insert into Industries (IndustryDesc) values ('CANNED, FROZEN & PRESERVD FRUIT, VEG & FOOD SPECIALTIES');
insert into Industries (IndustryDesc) values ('RETAIL-GROCERY STORES');
insert into Industries (IndustryDesc) values ('SERVICES-MEDICAL LABORATORIES');
insert into Industries (IndustryDesc) values ('SPECIAL INDUSTRY MACHINERY, NEC');
insert into Industries (IndustryDesc) values ('HOUSEHOLD FURNITURE');
insert into Industries (IndustryDesc) values ('GENERAL BLDG CONTRACTORS - RESIDENTIAL BLDGS');
insert into Industries (IndustryDesc) values ('SERVICES-AMUSEMENT & RECREATION SERVICES');
insert into Industries (IndustryDesc) values ('WHOLESALE-MOTOR VEHICLES & MOTOR VEHICLE PARTS & SUPPLIES');
insert into Industries (IndustryDesc) values ('GUIDED MISSILES & SPACE VEHICLES & PARTS');
insert into Industries (IndustryDesc) values ('MINING & QUARRYING OF NONMETALLIC MINERALS (NO FUELS)');
insert into Industries (IndustryDesc) values ('HEATING EQUIP, EXCEPT ELEC & WARM AIR; & PLUMBING FIXTURES');
insert into Industries (IndustryDesc) values ('RETAIL-RETAIL STORES, NEC');
insert into Industries (IndustryDesc) values ('MISCELLANEOUS FOOD PREPARATIONS & KINDRED PRODUCTS');
insert into Industries (IndustryDesc) values ('ELECTROMEDICAL & ELECTROTHERAPEUTIC APPARATUS');
insert into Industries (IndustryDesc) values ('CARPETS & RUGS');
insert into Industries (IndustryDesc) values ('MALT BEVERAGES');
insert into Industries (IndustryDesc) values ('BOTTLED & CANNED SOFT DRINKS & CARBONATED WATERS');
insert into Industries (IndustryDesc) values ('RADIO & TV BROADCASTING & COMMUNICATIONS EQUIPMENT');
insert into Industries (IndustryDesc) values ('COMPUTER STORAGE DEVICES');
insert into Industries (IndustryDesc) values ('SERVICES-VIDEO TAPE RENTAL');
insert into Industries (IndustryDesc) values ('PLASTICS PRODUCTS, NEC');
insert into Industries (IndustryDesc) values ('GOLD AND SILVER ORES');
insert into Industries (IndustryDesc) values ('NEWSPAPERS: PUBLISHING OR PUBLISHING & PRINTING');
insert into Industries (IndustryDesc) values ('RUBBER & PLASTICS FOOTWEAR');
insert into Industries (IndustryDesc) values ('STEEL WORKS, BLAST FURNACES & ROLLING MILLS (COKE OVENS)');
insert into Industries (IndustryDesc) values ('NATURAL GAS TRANSMISISON & DISTRIBUTION');
insert into Industries (IndustryDesc) values ('PAPERBOARD CONTAINERS & BOXES');
insert into Industries (IndustryDesc) values ('MISCELLANEOUS FABRICATED METAL PRODUCTS');
insert into Industries (IndustryDesc) values ('SERVICES-ENGINEERING, ACCOUNTING, RESEARCH, MANAGEMENT');
insert into Industries (IndustryDesc) values ('SPECIAL INDUSTRY MACHINERY (NO METALWORKING MACHINERY)');
insert into Industries (IndustryDesc) values ('WHOLESALE-MISC DURABLE GOODS');
insert into Industries (IndustryDesc) values ('PAINTS, VARNISHES, LACQUERS, ENAMELS & ALLIED PRODS');
insert into Industries (IndustryDesc) values ('ELECTRICAL WORK');
insert into Industries (IndustryDesc) values ('REFUSE SYSTEMS');
insert into Industries (IndustryDesc) values ('SERVICES-HELP SUPPLY SERVICES');
insert into Industries (IndustryDesc) values ('MEASURING & CONTROLLING DEVICES, NEC');
insert into Industries (IndustryDesc) values ('SERVICES-TO DWELLINGS & OTHER BUILDINGS');
insert into Industries (IndustryDesc) values ('GAS & OTHER SERVICES COMBINED');
insert into Industries (IndustryDesc) values ('CUTLERY, HANDTOOLS & GENERAL HARDWARE');
insert into Industries (IndustryDesc) values ('RETAIL-EATING & DRINKING PLACES');
insert into Industries (IndustryDesc) values ('RADIOTELEPHONE COMMUNICATIONS');
insert into Industries (IndustryDesc) values ('LEATHER & LEATHER PRODUCTS');
insert into Industries (IndustryDesc) values ('WHOLESALE-ELECTRONIC PARTS & EQUIPMENT, NEC');
insert into Industries (IndustryDesc) values ('AIRCRAFT & PARTS');
insert into Industries (IndustryDesc) values ('OPHTHALMIC GOODS');
insert into Industries (IndustryDesc) values ('SUGAR & CONFECTIONERY PRODUCTS');
insert into Industries (IndustryDesc) values ('SERVICES-MISCELLANEOUS AMUSEMENT & RECREATION');
insert into Industries (IndustryDesc) values ('AUTO CONTROLS FOR REGULATING RESIDENTIAL & COMML ENVIRONMENTS');
insert into Industries (IndustryDesc) values ('AIRCRAFT PARTS & AUXILIARY EQUIPMENT, NEC');
insert into Industries (IndustryDesc) values ('POULTRY SLAUGHTERING AND PROCESSING');
insert into Industries (IndustryDesc) values ('APPAREL & OTHER FINISHD PRODS OF FABRICS & SIMILAR MATL');
insert into Industries (IndustryDesc) values ('TRUCKING & COURIER SERVICES (NO AIR)');
insert into Industries (IndustryDesc) values ('SERVICES-EQUIPMENT RENTAL & LEASING, NEC');
insert into Industries (IndustryDesc) values ('WHOLESALE-DURABLE GOODS');
insert into Industries (IndustryDesc) values ('RAILROAD EQUIPMENT');
insert into Industries (IndustryDesc) values ('FABRICATED RUBBER PRODUCTS, NEC');
insert into Sector (SectorDesc) values ('LIFE SCIENCES');
insert into Sector (SectorDesc) values ('MANUFACTURING');
insert into Sector (SectorDesc) values ('TRADE & SERVICES');
insert into Sector (SectorDesc) values ('TECHNOLOGY');
insert into Sector (SectorDesc) values ('ENERGY & TRANSPORTATION');
insert into Sector (SectorDesc) values ('FINANCE');
insert into Sector (SectorDesc) values ('REAL ESTATE & CONSTRUCTION');
